### ISSUE TITLE
Error when running any of the commands

### ISSUE THREAD

**Issue by trodrigues** [zhaocai/alfred2-top-workflow#1]
```
ERROR  me.zhaowu.top : A fatal error has occurred. You may seek help in the Alfred supporting site, forum or raise an issue in the bug tracking site.
  #<NoMethodError: undefined method `ljust' for nil:NilClass>
  ./alfred2_top_workflow.rb:235:in `generate_feedback'  
./alfred2_top_workflow.rb:219:in `each'  
./alfred2_top_workflow.rb:219:in `generate_feedback'  
./alfred2_top_workflow.rb:259  
/Users/trodrigues/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.B69DA4EF-206C-4D10-A891-33BA2B8D29C6/bundle/ruby/1.8/gems/alfred-workflow-1.2.7/lib/alfred.rb:26:in `with_friendly_error'  
./alfred2_top_workflow.rb:253
```

**Comment by zhaocai** [comment]
can you run `ps -acwwwxo 'pid nice %cpu %mem state command'` and give me the output.

**Comment by zhaocai** [comment]
meanwhile, you can download the updated version. it should have fixed it.

**Comment by trodrigues** [comment]
Tried the new version with no success. Still getting the same error but on a different line:

```
ERROR  me.zhaowu.top : A fatal error has occurred. You may seek help in the Alfred supporting site, forum or raise an issue in the bug tracking site.
  #<NoMethodError: undefined method `ljust' for nil:NilClass>
  ./alfred2_top_workflow.rb:198:in `generate_feedback'  
./alfred2_top_workflow.rb:182:in `each'  
./alfred2_top_workflow.rb:182:in `generate_feedback'  
./alfred2_top_workflow.rb:229  
/Users/trodrigues/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.940CF1B5-FE33-4B7E-9218-0A30D6B0A19E/bundle/ruby/1.8/gems/alfred-workflow-1.2.7/lib/alfred.rb:26:in `with_friendly_error'  
./alfred2_top_workflow.rb:216
```

Here's the output of the command you asked for:

```
~ % ps -acwwwxo 'pid nice %cpu %mem state command'
  PID NI  %CPU %MEM STAT COMMAND
    1  0   0.0  0.0 Ss   launchd
   11  0   0.0  0.0 Ss   UserEventAgent
   12  0   0.0  0.0 Ss   kextd
   14  0   0.0  0.0 Ss   notifyd
   15  0   0.0  0.1 Ss   securityd
   16  0   0.0  0.0 Ss   diskarbitrationd
   17  0   0.0  0.0 Ss   configd
   18  0   0.0  0.0 Ss   powerd
   19  0   0.0  0.0 Ss   distnoted
   20  0   0.0  0.0 Ss   syslogd
   22  0   0.0  0.1 Ss   opendirectoryd
   25  0  54.7  0.2 Ss   coreservicesd
   51  0   0.0  0.1 Ss   fseventsd
   58  0   0.0  0.0 Ss   mDNSResponder
   59  0   0.0  0.0 Ss   networkd
  166  0   0.0  0.0 Ss   ntpd
  167  0   0.0  0.0 Ss   cron
  169 10   0.0  0.0 SNs  warmd
  170  0   0.0  0.0 Ss   usbmuxd
  172  0   0.0  0.0 Ss   SystemStarter
  174  0   0.0  0.0 Ss   stackshot
  175  0   0.0  0.0 Ss   SleepServicesD
  177  0   0.0  0.0 Ss   revisiond
  182  0   0.0  2.2 Ss   mds
  185  0   0.0  0.2 Ss   loginwindow
  186  0   0.0  0.1 Ss   locationd
  187  0   0.0  0.0 Ss   KernelEventAgent
  188  0   0.0  0.0 Ss   kdc
  190  0   0.0  0.0 Ss   hidd
  192  0   0.0  0.0 Ss   dynamic_pager
  195  0   0.0  0.0 Ss   corestoraged
  196  0   0.0  0.0 Ss   appleeventsd
  200  0   0.0  0.0 Ss   autofsd
  201  0   0.0  0.1 Ss   apsd
  202  0   0.0  0.1 Ss   aosnotifyd
  203  0   0.0  0.3 Ss   socketfilterfw
  207  0   0.0  0.2 Ss   ccc_helper
  208  0   0.0  0.1 Ss   iStatMenusDaemon
  215  0   1.2  1.6 Ss   WindowServer
  416  0   0.0  0.0 Ss   CVMServer
  432  0   0.7  0.1 Ss   coreaudiod
  433  0   0.0  0.0 Ss   logind
  446  0   0.0  0.0 Ss   launchd
  449  0   0.0  0.1 S    UserEventAgent
  450  0   0.0  0.1 S    distnoted
  459  0   0.4  0.4 S    Dock
  460  0   0.0  0.1 S    talagent
  462  0   0.1  1.2 S    Finder
  465  0   0.0  0.0 S    pboard
  468  0   0.0  0.1 S    usernoted
  472  0   0.0  0.2 S    NotificationCenter
  478  0   0.0  0.0 S    imagent
  486  0   0.0  0.1 S    PCKeyboardHack
  488  0   0.0  0.1 S    KeyRemap4MacBook
  489  0   0.0  0.2 S    SIMBL Agent
  490  0   0.0  0.0 S    NML2NDeviceObserver
  492  0   0.0  0.0 S    iStatMenusAgent
  495  0   0.0  0.3 S    1PasswordAgent
  498  0   0.0  0.0 S    SpotifyWebHelper
  501  0   0.0  0.1 S    CCC User Agent
  502  0   0.0  0.1 S    Folder Actions Dispatcher
  627  0   0.0  0.1 S    fontd
  721  0   0.0  0.0 Ss   filecoordinationd
  745  0   0.0  0.1 Ss   com.apple.dock.extra
  775 20   0.0  0.0 SNs  netbiosd
  824  0   0.0  0.0 S    NetworkBrowserAgent
 1015  0   0.0  0.1 S    Caffeine
 1017  0   0.0  0.2 S    Bowtie
 1020  0   0.0  0.2 S    Synergyd
 1022  0   0.0  0.6 S    Hiss
 1024  0   0.0  0.2 S    iTeleport Connect
 1025  0   4.3  0.6 S    Dropbox
 1037  0   0.0  0.1 S    Cloud
 1038  0   0.1  0.4 S    Alfred 2
 1039  0   0.0  0.1 Ss   synergys
 1041  0   0.0  0.1 S    System Events
 1042  0   0.0  0.0 S    lsboxd
 1043  0   0.0  0.0 Ss   CloudRaindropHelper
 1172  0  18.7  1.1 S    Adium
 1176  0   1.8  1.3 S    Skype
 1179  0   0.0  0.1 S    AppleSpell
 1186  0   0.7  4.2 S    Google Chrome
 1189  0   0.0  4.1 S    Google Chrome Helper
 1190  0   0.0  0.1 S    Image Capture Extension
 1192  0   0.0  0.2 S    Google Chrome Helper
 1193  0   2.6  0.6 S    iTerm
 1194  0   0.0  2.9 S    Google Chrome Helper
 1195  0   0.0  0.1 S    CIJScannerRegister
 1197  0   0.5  0.7 S    Google Chrome Helper
 1199  0   0.0  0.1 S    iA Writer
 1200  0   0.0  0.1 S    librariand
 1201  0   0.0  0.1 S    ubd
 1202  0   0.0  0.0 Ss   VDCAssistant
 1203  0   0.0  0.0 ?Es  (zsh)
 1205  0   0.0  0.0 ?Es  (zsh)
 1206  0   0.0  0.0 Z    (zsh)
 1302  0   0.0  0.4 S    Google Chrome Helper
 1311  0   0.1  3.5 S    Google Chrome Helper
 1312  0   0.1  0.7 S    Google Chrome Helper
 1323  0   0.0  0.3 S    Google Chrome Helper
 1324  0   0.1  0.6 S    Google Chrome Helper
 1325  0   0.0  0.3 S    Google Chrome Helper
 1329  0   7.5  0.7 S    Google Chrome Helper
 1330  0   0.0  0.3 S    Google Chrome Helper
 1331  0   0.0  0.5 S    Google Chrome Helper
 1334  0   0.1  0.6 S    Google Chrome Helper
 1335  0   0.0  0.2 S    Google Chrome Helper
 1336  0   0.0  0.2 S    Google Chrome Helper
 1337  0   0.0  0.5 S    Google Chrome Helper
 1338  0   0.0  0.5 S    Google Chrome Helper
 1339  0   0.0  0.4 S    Google Chrome Helper
 1348  0   0.1  0.7 S    VirtualBox
 1352  0   0.0  0.0 S    VBoxXPCOMIPCD
 1354  0   0.0  0.1 S    VBoxSVC
 1361  0   0.0  0.4 S    Google Chrome Helper
 1371  0   0.0  0.4 S    Google Chrome Helper
 1384  0   5.6  2.0 S    Google Chrome Helper
 1387  0   0.0  0.1 S    Google Chrome Helper EH
 1389  0   0.0  0.4 S    Google Chrome Helper
 1390  0   0.0  0.5 S    Google Chrome Helper
 1392  0   0.0  0.4 S    Google Chrome Helper
 1396  0   0.0  0.4 S    Google Chrome Helper
 1397  0   0.0  0.4 S    Google Chrome Helper
 1398  0   0.0  0.9 S    Google Chrome Helper
 1403  0   0.0  0.5 S    Google Chrome Helper
 1404  0   0.0  0.6 S    Google Chrome Helper
 1405  0   0.0  0.5 S    Google Chrome Helper
 1406  0   0.0  0.5 S    Google Chrome Helper
 1408  0   0.0  0.7 S    Google Chrome Helper
 1409  0   0.0  0.6 S    Google Chrome Helper
 1410  0   0.0  0.6 S    Google Chrome Helper
 2208  0   0.0  0.0 Ss   syspolicyd
 2310  0   0.0  0.8 S    Google Chrome Helper
 2428  0   0.0  0.6 S    Google Chrome Helper
 2745  0   0.0  0.0 S    iTunesHelper
 2809  0   0.0  0.0 S    ssh-agent
 2955  0  10.6  1.2 S    Spotify
 2957  0   0.0  0.1 Ss   Bowtie Butler
 2959  0   0.0  1.9 S    iTunes
 2961  0   0.0  0.0 Ss   CloudRaindropHelper
 2963  0   0.0  0.0 S    ath
 2965  0   0.0  0.0 S    ath
 3533  0   0.2  0.4 S    SystemUIServer
 4283  0   0.0  0.1 S    SizeUp
 4292  0   0.0  0.2 S    witchdaemon
 4571  0   0.0  0.0 Z    (zsh)
 6342  0   0.0  0.1 S    DashboardClient
 6343  0   0.3  0.3 S    DashboardClient
 6395  0   0.0  0.0 Z    (zsh)
 7395  0   0.0  0.5 S    Google Chrome Helper
12940  0   0.0  0.1 S    storeagent
12963  0   0.0  0.0 Ss   installd
12970  0   0.0  0.0 S    maspushagent
12990  0   0.0  1.3 S    Tweetbot
15499  0   0.0  0.0 Ss   blued
16216  0   0.0  0.0 S    tuxera_ntfs_daemon
16218  0   0.0  0.2 Ss   tuxera_ntfs
16349  0   0.0  0.4 S    Google Chrome Helper
16409  0   0.0  0.0 S    helpd
20620  0   0.0  0.0 Z    (zsh)
20799  0   0.0  0.4 S    Google Chrome Helper
21380  0   0.0  0.2 S    Carbon Copy Cloner
21895  0   0.0  0.5 S    Google Chrome Helper
22088  0   0.1  0.8 S    Transmission
22230  0   0.0  0.5 S    Google Chrome Helper
23244  0   0.0  0.6 S    Google Chrome Helper
23360  0   0.1  2.1 S    Google Chrome Helper
23483  0  10.2  5.8 S    VirtualBoxVM
24709  0   0.0  0.5 S    Google Chrome Helper
25014  0   0.0  0.2 S    Console
25905  0   0.0  0.8 S    Google Chrome Helper
25954  0   0.0  0.5 S    Google Chrome Helper
29627  0   0.0  0.0 S    dbfseventsd
29628  0   0.0  0.1 S    dbfseventsd
29629  0   0.0  0.0 S    dbfseventsd
33846  0   0.0  0.3 S    Disk Utility
33848  0   0.0  0.0 Ss   diskmanagementd
33893  0   0.0  0.0 S    cfprefsd
33894  0   0.0  0.0 Ss   cfprefsd
33895  0   0.0  0.0 Ss   launchd
33898  0   0.0  0.0 S    distnoted
33899  0   0.0  0.0 S    cfprefsd
33900  0   0.0  0.4 S    CalendarAgent
33901  0   0.0  0.0 S    tccd
33903  0   0.0  0.1 Ss   xpcd
33922 17   4.0  0.4 SN   mdworker
33926  0  29.7  0.1 R    pbs
33941  0   0.0  0.1 Ss   com.apple.iCloudHelper
34137  0   0.0  0.9 S    Google Chrome Helper
34138  0   0.0  0.0 Ss   ocspd
34142  0   0.0  1.0 S    Google Chrome Helper
34148  0   0.0  0.0 Ss   taskgated
34151  0   0.0  0.4 S    Alfred Preferences
34153  0   0.0  0.3 S    CVMCompiler
34213  0   0.0  0.4 S    Google Chrome Helper
39535  0   0.0  1.1 S    Sublime Text 2
45054  0   0.0  0.4 S    Google Chrome Helper
45111  0   0.0  0.5 S    Google Chrome Helper
49331  0   0.4  0.5 S    Google Chrome Helper
49476  0   0.0  0.0 Ss   CloudRaindropHelper
49709  0   0.0  0.5 S    Google Chrome Helper
51746  0   0.0  0.0 S    GoogleTalkPlugin
67916  0   0.0  0.6 S    Google Chrome Helper
73782  0   0.0  0.7 S    Google Chrome Helper
87213  0   0.0  0.8 S    Google Chrome Helper
96887  0   0.0  0.0 S    ssh
97005  0   0.0  0.0 S    ssh
97145  0   0.0  0.0 Z    (zsh)
 3169  0   0.0  0.0 Ss+  zsh
 4605  0   0.0  0.0 Ss+  zsh
 5313  0   0.0  0.0 Ss+  zsh
99296  0   0.0  0.0 Ss+  zsh
 3879  0   0.0  0.0 Ss+  zsh
 4187  0   0.0  0.0 Ss+  zsh
 8791  0   0.0  0.0 Ss+  zsh
15556  0   0.0  0.0 Ss   zsh
16289  0   0.0  0.0 S+   ssh
22859  0   0.0  0.0 Ss+  zsh
35136  0   0.4  0.0 Ss   zsh
35159  0   0.0  0.0 R+   ps
```

**Comment by zhaocai** [comment]
I guess it is the `?Es` state symbols. '?' is not defined in my workflow.

```
1203  0   0.0  0.0 ?Es  (zsh)
1205  0   0.0  0.0 ?Es  (zsh)
```

should be fixed now. you can use http://www.alfredforum.com/topic/1582-alleyoop-update-alfred-workflows/ to update.

**Comment by trodrigues** [comment]
Yup! That worked beautifully. Thanks for the Alleyoop tip by the way! Really useful stuff.
