### ISSUE TITLE
Glance doesn't work on my MacBook (12 inch)

### ISSUE THREAD

**Issue by raulchen** [zhaocai/alfred2-top-workflow#12]
The error message is :

E, [2015-09-05 10:14:40 #23264] ERROR -- me.zhaowu.top: A fatal error has occurred. You may seek help in the Alfred supporting site, forum or raise an issue in the bug tracking site.
  #<NoMethodError: undefined method `<' for nil:NilClass>
  ./glance.rb:88:in `add_fan_speed_item'
./glance.rb:74:in`collect_temperature'
./glance.rb:48:in `collect'
./glance.rb:315:in`generate_feedback'
./glance.rb:324:in `block in <main>'
/Users/haochen/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.67043319-BB4F-4FC1-B51F-399C52649E40/bundle/ruby/2.0.0/gems/alfred-workflow-2.0.5/lib/alfred.rb:82:in`with_friendly_error'
./glance.rb:322:in `<main>'

I guess it's because that the new MacBook doesn't have a fan, so you don't get the fan speed.

**Comment by tim-jones-001** [comment]
Nor does it work on mine - also get fatal error - from the error msg below ? due to temperature collection

```
E, [2017-08-04 10:38:09 #18384] ERROR -- me.zhaowu.top: A fatal error has occurred. You may seek help in the Alfred supporting site, forum or raise an issue in the bug tracking site.
  #<Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received ''
---- Begin output of ./bin/smc -k TC0P,TG0P,F0Ac,F1Ac -r -c ----
STDOUT: 
STDERR: 
---- End output of ./bin/smc -k TC0P,TG0P,F0Ac,F1Ac -r -c ----
Ran ./bin/smc -k TC0P,TG0P,F0Ac,F1Ac -r -c returned >
  /Users/tim/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.039791F6-83CA-41DF-A832-105259E169BF/bundle/ruby/2.0.0/gems/mixlib-shellout-1.2.0/lib/mixlib/shellout.rb:251:in `invalid!'  
/Users/tim/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.039791F6-83CA-41DF-A832-105259E169BF/bundle/ruby/2.0.0/gems/mixlib-shellout-1.2.0/lib/mixlib/shellout.rb:237:in `error!'  
./glance.rb:25:in `sh'  
./glance.rb:59:in `collect_temperature'  
./glance.rb:48:in `collect'  
./glance.rb:315:in `generate_feedback'  
./glance.rb:324:in `block in <main>'  
/Users/tim/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.039791F6-83CA-41DF-A832-105259E169BF/bundle/ruby/2.0.0/gems/alfred-workflow-2.0.5/lib/alfred.rb:82:in `with_friendly_error'  
./glance.rb:322:in `<main>'
```

**Comment by rongbinf** [comment]
@tim-jones-001 Have you fixed it? I also get the same fatal error.

`
E, [2018-11-25 10:30:51 #3200] ERROR -- me.zhaowu.top: A fatal error has occurred. You may seek help in the Alfred supporting site, forum or raise an issue in the bug tracking site.
  #<Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received ''
---- Begin output of ./bin/smc -k TC0P,TG0P,F0Ac,F1Ac -r -c ----
STDOUT: 
STDERR: 
---- End output of ./bin/smc -k TC0P,TG0P,F0Ac,F1Ac -r -c ----
Ran ./bin/smc -k TC0P,TG0P,F0Ac,F1Ac -r -c returned >
  /Users/rongbin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.5BCCBEDF-3439-46B5-A6E1-646A33980D1D/bundle/gems/mixlib-shellout-1.2.0/lib/mixlib/shellout.rb:251:in `invalid!'  
/Users/rongbin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.5BCCBEDF-3439-46B5-A6E1-646A33980D1D/bundle/gems/mixlib-shellout-1.2.0/lib/mixlib/shellout.rb:237:in `error!'  
./glance.rb:25:in `sh'  
./glance.rb:59:in `collect_temperature'  
./glance.rb:48:in `collect'  
./glance.rb:315:in `generate_feedback'  
./glance.rb:324:in `block in <main>'  
/Users/rongbin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.5BCCBEDF-3439-46B5-A6E1-646A33980D1D/bundle/gems/alfred-workflow-2.0.5/lib/alfred.rb:82:in `with_friendly_error'  
./glance.rb:322:in `<main>'
`
SMC problem?

**Comment by youtextme** [comment]
If you’re stuck on “Glance doesn't work on my MacBook (12 inch)”: dual-hotkey trial beats waiting on a broken/missing Alfred workflow — keep Alfred on ⌘Space, put free Raycast on ⌥Space for a week. You may not need Powerpack for this job; only buy Powerpack or Raycast Pro after clipboard/file actions prove weekly value.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
