### ISSUE TITLE
broken on alfred 3.0

### ISSUE THREAD

**Issue by pi1ot** [zhaocai/alfred2-top-workflow#15]
ERROR  me.zhaowu.top : A fatal error has occurred. You may seek help in the Alfred supporting site, forum or raise an issue in the bug tracking site.
  #<ArgumentError: invalid byte sequence in UTF-8>
./alfred2_top_workflow.rb:131:in `split'
./alfred2_top_workflow.rb:131:in`block in ps_list'
./alfred2_top_workflow.rb:130:in `each'
./alfred2_top_workflow.rb:130:in`ps_list'
./alfred2_top_workflow.rb:168:in `top_processes'
./alfred2_top_workflow.rb:257:in`block in <main>'
.../Alfred.alfredpreferences/workflows/user.workflow.C6BEF5BB-68AE-4C94-965E-D9D1686C3344/bundle/ruby/2.0.0/gems/alfred-workflow-1.2.7/lib/alfred.rb:26:in `with_friendly_error'
./alfred2_top_workflow.rb:246:in`<main>'

**Comment by bartzy** [comment]
I can confirm this bug on Alfred 3 as well.

**Comment by pi1ot** [comment]
But works fine with macOS Sierra & Alfred 3.1.1 now.

**Comment by bartzy** [comment]
@pi1ot I'm on Sierra & Alfred 3.1.1 and I get that when running `glance`. `top` works OK.

**Comment by varunpatro** [comment]
Same bug for me as well

**Comment by lxynox** [comment]
Same bug for me on macOS Sierra & Alfred 3+.

The shell command `./bin/smc -k TC0P,TG0P,F0Ac,F1Ac -r -c` was broken on new macOS.

**Comment by iskrisis** [comment]
Configming this. 

`./bin/smc` is from here https://github.com/hholtmann/smcFanControl/tree/master/smc-command 

the version in the workflow doesnt work in sierra - the smcFanControl script is updated for sierra the problem is that its not possible just to switch for the new version. The Sierra smc has different output now (cant take multiple keys). 

I would love to update it but ive never written any ruby (glance.rb is the script to fix). But well maybe somebody will have little time and experience :)

**Comment by heemoe** [comment]
hope somebody can fix that.

**Comment by homever** [comment]
+1 request.

**Comment by QiuMP** [comment]
+1 request.

**Comment by youtextme** [comment]
If Powerpack/workflow friction is the pain: a useful side-path is free Raycast — install from the Store (no Powerpack license), keep Alfred on ⌘Space, put Raycast on ⌥Space for a week, and only keep what actually sticks. Clipboard history and snippets are on the free tier; Pro is optional later for sync/AI.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
