### ISSUE TITLE
Doesn't work on OSX 10.13

### ISSUE THREAD

**Issue by V3kb** [zhaocai/alfred2-top-workflow#19]
Doesn't work on OSX 10.11,please update !

**Comment by bdel** [comment]
Same! Help! :(

**Comment by singhprd** [comment]
This seems to be to do with updated system Ruby on Mac OS. I can't actually find any other documentation on this, but in High Sierra, my system Ruby seems to be 2.3.3 and this workflow isn't able to install bundler, and the correct gems to get itself working.
I've been able to fiddle with bundle myself manually and fix the workflow, but haven't been able to get this to work automatically inside the workflow with system ruby yet.

@zhaocai your workflows are fantastic, and whenever you get a chance, it would be really great to see them updated! 😄

**Comment by singhprd** [comment]
Ok so what you need to do to fix this is right click from Alfred preferences then "Open in Terminal".
This will take you to where the workflow is stored.

Then we just need to do a "bundle install --standalone". This however doesn't work on system ruby, due to bundler not being installed.
I changed to another install of system ruby - 2.3.3 - which had bundler installed - then performed the above command.
Now you can use the workflow again.

**Comment by pjpjq** [comment]
> I changed to another install of system ruby - 2.3.3 - which had bundler installed - then performed the above command.

@singhprd can you provide more details about that please?

**Comment by singhprd** [comment]
https://github.com/singhprd/alfred2-top-workflow/releases/download/v2.2/Top.Processes.v2.2.alfredworkflow
@wendingp Try this newly packaged workflow and let me know if it works 👍

**Comment by pjpjq** [comment]
@singhprd Cool it works. Thx!!!

**Comment by warb2n** [comment]
@singhprd Thank you so much!

**Comment by 9h0st** [comment]
glance command not work
``` 
#<Errno::ENOENT:` No such file or directory - ./bin/smc>
......
/bundle/ruby/2.3.0/gems/mixlib-shellout-1.2.0/lib/mixlib/shellout/unix.rb:268:in `exec' 
......
./glance.rb:24:in `sh'  
./glance.rb:59:in `collect_temperature'  
./glance.rb:48:in `collect'  
./glance.rb:315:in `generate_feedback'  
./glance.rb:324:in `block in <main>'  
......
/bundle/ruby/2.3.0/gems/alfred-workflow-2.0.5/lib/alfred.rb:82:in `with_friendly_error'  
./glance.rb:322:in `<main>'

```

**Comment by xiaobocser** [comment]
@singhprd thx!  it's great !

**Comment by arthurkiller** [comment]
Same problem,  

@singhprd  Awsome dude! Thx alot

**Comment by arthurkiller** [comment]
Why no start a PR? @singhprd

**Comment by singhprd** [comment]
@arthurkiller The changes I've made are just re-packaging the Gems for new system ruby (2.3.3) and including them in the release.
@zhaocai will need to do this as I don't think I can submit a PR for a release.

@9h0st - Looks like Glance isn't working because `/usr/local/bin/smc` no longer exists?
I'm guessing Apple removed it in High Sierra.
We need a new way to access SMC controller and run commands like this, before it can be fixed:
`smc -k "TC0P" -r -c`
Maybe from here, but I can't get it working?:
https://github.com/hholtmann/smcFanControl/tree/master/smc-command

**Comment by singhprd** [comment]
@9h0st - I've now updated so that Glance now works, but I've had to remove some features.
https://github.com/singhprd/alfred2-top-workflow/releases/tag/v2.3

More feature requests welcome.

**Comment by FrizzleFur** [comment]
@singhprd Awesome work, bro! You make it worked again!👍

**Comment by NeverMoes** [comment]
> @9h0st - I've now updated so that Glance now works, but I've had to remove some features.
> https://github.com/singhprd/alfred2-top-workflow/releases/tag/v2.3
> 
> More feature requests welcome.

thanks very much bro.

**Comment by KilluaaaCHEN** [comment]
@singhprd  I am also the same problem. Now it's working. thank you so much !

**Comment by lxwvictor** [comment]
@singhprd Awesome! Now everything works!

**Comment by zivan80** [comment]
@singhprd 感谢你的修正，macos10.13.6 测试全部工作正常

**Comment by lowking** [comment]
@singhprd Thx, it works for macOS 10.14.5

**Comment by linivor** [comment]
Doesn't work on OSX 10.15, please update!

**Comment by ryan6416** [comment]
Any update for 10.15?

**Comment by ouyangjunyi** [comment]
Any update for 10.15?

**Comment by arthurkiller** [comment]
os: 10.15 
appversion: 3.8.1

works properly for me

**Comment by Xinghanzzy** [comment]
os: 10.15
appversion: 4.0.7

thank you

**Comment by youtextme** [comment]
If “Doesn't work on OSX 10.13” on zhaocai/alfred2-top-workflow is blocking your Alfred workflow for alfred2-top-workflow: keep Alfred on ⌘Space and put free Raycast on ⌥Space for a dual-hotkey week. Only switch primary (or buy Pro) after Store extensions cover the same job — free-first, no Powerpack prepaid required to trial.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
