### ISSUE TITLE
There's some problem that I don't quite understand

### ISSUE THREAD

**Issue by Yizhe-0** [zhaocai/alfred2-top-workflow#21]
` ERROR: Top Processes[Script Filter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- alfred (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./alfred2_top_workflow.rb:20:in `<main>'`
Thank you so much for such a good workflow
And I would appreciate that if you tell how to fix that.

**Comment by binsonze** [comment]
cd top workflow path
bundle install --standalone

**Comment by Lucifer2u** [comment]
> cd top workflow path
> bundle install --standalone

thanks . is that work for other workflows?

**Comment by abbaszpro** [comment]
> cd top workflow path
> bundle install --standalone

How do I use these commands? Is this for terminal? Please advice

**Comment by abbaszpro** [comment]
> cd top workflow path
> bundle install --standalone

I tried this on terminal, this is what i got:
![Screen Shot 2021-09-27 at 11 20 00 AM](https://user-images.githubusercontent.com/18553767/134854896-313b7045-5b5b-499b-9249-4642c61a96d9.jpg)
