### ISSUE TITLE
glance/lsof crash on null dereference.

### ISSUE THREAD

**Issue by pedramamini** [zhaocai/alfred2-top-workflow#5]
Tried installing through repo and standard point and click, both resulted in the following error:

```
$ tail /Users/pedram/Library/Logs/Alfred-Workflow.log

E, [2013-11-12 00:55:42 #10433] ERROR -- me.zhaowu.top: A fatal error has occurred. You may seek help in the Alfred supporting site, forum or raise an issue in the bug tracking site.
  #<NoMethodError: undefined method `split' for nil:NilClass>
  ./glance.rb:46:in `collect_temperature'
./glance.rb:32:in `collect'
./glance.rb:284:in `generate_feedback'
./glance.rb:293:in `block in <main>'
/Users/pedram/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.316E8A5F-6CC4-42E1-93C2-5D379CEECA78/bundle/ruby/2.0.0/gems/alfred-workflow-2.0.5/lib/alfred.rb:82:in `with_friendly_error'
./glance.rb:291:in `<main>'
```

**Comment by zhaocai** [comment]
try the updated package

**Comment by pedramamini** [comment]
Just did:

```
# Logfile created on 2013-11-12 03:08:07 -0600 by logger.rb/36483
E, [2013-11-12 03:08:07 #50620] ERROR -- me.zhaowu.top: A fatal error has occurred. You may seek help in the Alfred supporting site, forum or raise an issue in the bug tracking site.
  #<TypeError: nil can't be coerced into Float>
  ./glance.rb:66:in `+'
./glance.rb:66:in `collect_temperature'
./glance.rb:48:in `collect'
./glance.rb:302:in `generate_feedback'
./glance.rb:311:in `block in <main>'
/Users/pedram/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.EA5C4596-327D-456C-A012-BA4C83CBF41E/bundle/ruby/2.0.0/gems/alfred-workflow-2.0.5/lib/alfred.rb:82:in `with_friendly_error'
./glance.rb:309:in `<main>'
```

**Comment by zhaocai** [comment]
please run `./bin/smc -k TC0P,TG0P,F0Ac,F1Ac -r -c` in the workflow folder in the terminal and paste the output here.

**Comment by pedramamini** [comment]
```
$ ./bin/smc -k TC0P,TG0P,F0Ac,F1Ac -r -c
:TC0P => 34.000 ,
:TG0P => nil,
:F0Ac => 1314.00 ,
:F1Ac => nil,
```

This is on most recent release of MBP + Mavericks.

**Comment by zhaocai** [comment]
get nil for
- Fan1 Actual RPM
- GPU 0 Proximity temp

this is wired because it returns correct value in my Macbook pro. 

Anyway, I add code the check for nil, try the updated package

**Comment by pedramamini** [comment]
It is odd. Thanks for the back and forth debugging. Works now.
